### ISSUE TITLE
Command line arg to Start with specific wordList

### ISSUE THREAD

**Issue by sl5net** [ManiacDC/TypingAid#83] opened 2017-03-01 19:08 UTC
Workaround
Copy the project as many times as you need contexts. Rename the respective folders according to the corresponding context (e.g., C # or JavaScript). Create a AHK which makes sure that only one of these is started at the same time and that it is always started correctly.
Or you simply modify the original AHK.

**Comment by ManiacDC** [comment] 2017-03-01 19:54
This is a duplicate of https://github.com/ManiacDC/TypingAid/issues/32. Thanks!

**Closed as completed** 2017-03-01 19:54 UTC
Labels: duplicate

**Comment by sl5net** [comment] 2017-03-04 17:02
i did it. it works without "lerning mode"
i did some little modifikations and a seperate short controller script (it changes the wordlist automatically for nearly every window. the first entry in every wordlist is the localtion where itself is stored.

i documented here: https://autohotkey.com/boards/viewtopic.php?p=135218#p135218
